### ISSUE TITLE
Why libuv?

### ISSUE THREAD

**Issue by enumag** [amphp/http-server-static-content#11]
In [documentation](https://amphp.org/http-server/production) there is a note that I should use libuv when using this. However the reason for that or what happens if it isn't used is missing.

Also if it is important it should be mentioned in the readme of this package.

I can send PRs if you can explain the reasons to me.

**Comment by kelunik** [comment]
I guess this is no longer really relevant with our current `amphp/file`. It can also be `eio` or `parallel`. @trowski What do you think?

**Comment by trowski** [comment]
We should recommend using some sort of an extension, preferably `uv` or `eio`. I've never tried `parallel` in production, but I assume it would be slower because IPC is done in PHP instead of C.

**Comment by enumag** [comment]
Solved by https://github.com/amphp/http-server/pull/298
