### ISSUE TITLE
Support for amphp/file v2

### ISSUE THREAD

**Issue by bzikarsky** [amphp/http-server-static-content#14]
This amphp library is blocking the amphp/file v2 upgrade in our dependency chain.

**Comment by kelunik** [comment]
Adding support for v2 should be straight forward. Do you want to take a look?

**Comment by bzikarsky** [comment]
I will likely not get to it in the next weeks. But probably no one else will run into this "issue" on the same time span. If it's still open when I get back to this, I'll look into it.

**Comment by enumag** [comment]
It seems amphp/file isn't used all that much here. I think you just need to allow it in composer,json + add a class_exists condition [here](https://github.com/amphp/http-server-static-content/blob/532280d2b84d34134a65fe5f7950f1d4ecdd1809/src/DocumentRoot.php#L230).

EDIT: Ah nvm, the Driver API has been changed as well it seems. So yeah more changes will be needed.

@kelunik I think you should specify whether you want to just upgrade to file 2.0 or if you want to have a fallback similar to what I did [here](https://github.com/amphp/http-client/pull/295).

**Comment by trowski** [comment]
I did this time time ago and failed to ever tag a version – too busy with Amp v3 I suppose.
