### ISSUE TITLE
Cannot run example: Missing dependency http-server-roter

### ISSUE THREAD

**Issue by prolic** [amphp/http-server-static-content#17]
In order to execute the example the amphp/http-server-router dependency has be installed as well.

**Comment by prolic** [comment]
This is for amphp v3. By the way, same problem is for amphp/log - it's also required for the example to be able to run.

**Comment by trowski** [comment]
Both of these dependencies are listed in the `require-dev` section of `composer.json`. Nonetheless, I added a note about it in the example.
