### ISSUE TITLE
Serving from a subdirectory

### ISSUE THREAD

**Issue by bwoebi** [amphp/http-server-static-content#5]
If a path looks like `/static/css/screen.css`, and we want to only have a docroot for things inside `/static`, what's the way to go? (I.e. I have a file `/foo/bar/css/screen.css` and want to map `/foo/bar` onto `/static`)

Or another use case: in combination with prefixed Routers. Currently DocumentRoot looks at the full URI path and dispatches from there.

I know of amphp/http-server-router#3 which could solve the second case in particular, but we probably should provide a generic solution for this.

**Comment by kelunik** [comment]
I guess a generic `StripPrefixMiddleware` can do that in combination with the router. We could also add other middlewares like a `PrefixMiddleware`. How about a package for those named `amphp/http-server-uri-rewrite`?

**Comment by kelunik** [comment]
I'm going to close this issue, as it's not at the right place. Such a middleware can always be added in a separate repository or in the main repository.
